server:
  port: 8081
  servlet:
    context-path: /final-project-api

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/final-project
          jwk-set-uri: http://localhost:8080/auth/realms/final-project/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include:        - health
        - metrics
        - loggers

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: final-project
  resource: final-project-client
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username